spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.150.128:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.128:8848
  application:
    name: gulimall-order
server:
  port: 9000